### ISSUE TITLE
Intent of ONSPD_download isn't clear.

### ISSUE THREAD

**Issue by rossjones** [OpenAddressesUK/common-ETL#9]
Is this just trying to get the latest file, or all of the files it can find? Seems to be trying to find the latest, but doesn't check it is already exists locally etc.

**Comment by Floppy** [comment]
Good point, thanks for raising it! It will try to get the latest file it can find, and you're right, it will overwrite anything with the same name in the working directory. It's "designed" (as far as these things are in alpha) to work on a one-off ingester VM really.

**Comment by rossjones** [comment]
great, thanks.  Working as designed.  Will fix my fork up a bit.
